# server conf
server:
  port: 18001
  servlet:
    context-path: /

dubbo:
  application:
    name: duboo-provider
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol.name: dubbo