# server conf
server:
  port: 18002
  servlet:
    context-path: /

dubbo:
  application:
    name: duboo-consumer
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol.name: dubbo
  consumer:
    check: false