server:
  port: 18084

spring:
  # 模板配置
  thymeleaf:
    cache: false
    # 这个是配置模板路径的，默认就是templates，可不用配置
    prefix: classpath:/templates/
    # 这个可以不配置，检查模板位置
    check-template-location: true
    # 下面3个不做解释了，可以不配置
    suffix: .html
    encoding: UTF-8
    # 模板的模式
    mode: HTML5

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workflow?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: sxt7777777

  # 工作流配置
  activiti:
    check-process-definitions: false
---
spring:
  profiles: dev
  # thymeleaf模板配置
